// src/pages/ReadingPage.jsx
//
// AI Reading page — /reading
// Loads natal + aspects from localStorage, lets user pick a focus,
// calls Gemini Flash, and displays the synthesized reading.

import { useState, useEffect, useRef } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { generateReading, isOracleConfigured as isGeminiConfigured, FOCUS_AREAS } from '../lib/oracle';
import {
  saveReading,
  getRecentReadings,
  getLatestReading,
} from '../lib/readingCache';
import { PlanetIcon, UiIcon } from '../components/EphiIcons.jsx';
import { getPlanetPositions } from '../lib/ephemeris';
import { getActiveAspects } from '../lib/aspects';
import EphiMarkdown from '../components/EphiMarkdown';
import ChartWheel from '../components/AstroChartWheel.jsx';
import { generateAspectReading } from '../lib/oracle';
import AdSlot from '../components/AdSlot.jsx';
import { store } from '../lib/store';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getNatalFromStorage() {
  try {
    return store.getJSON('astro_natal');
  } catch { return null; }
}

function getAspectsFromStorage() {
  try {
    return store.getJSON('astro_aspects');
  } catch { return null; }
}

function timeAgo(isoStr) {
  const diff = Date.now() - new Date(isoStr).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1)  return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function FocusSelector({ selected, onChange, disabled }) {
  return (
    <div className="reading-focus-row">
      {FOCUS_AREAS.map((f) => (
        <button
          key={f.value}
          className={`reading-focus-btn ${selected === f.value ? 'active' : ''}`}
          onClick={() => !disabled && onChange(f.value)}
          disabled={disabled}
        >
          <span className="reading-focus-emoji">{f.emoji}</span>
          <span>{f.label}</span>
        </button>
      ))}
    </div>
  );
}

function LoadingState({ focus }) {
  const focusLabel = FOCUS_AREAS.find((f) => f.value === focus)?.label || 'General';
  const [dot, setDot] = useState(0);

  useEffect(() => {
    const t = setInterval(() => setDot((d) => (d + 1) % 4), 500);
    return () => clearInterval(t);
  }, []);

  const messages = [
    'Reading the current sky…',
    'Consulting your natal chart…',
    `Weaving your ${focusLabel} reading…`,
    'Synthesizing the transits…',
    'Almost ready…',
  ];
  const [msgIdx, setMsgIdx] = useState(0);

  useEffect(() => {
    const t = setInterval(() => setMsgIdx((i) => (i + 1) % messages.length), 2200);
    return () => clearInterval(t);
  }, []);

  return (
    <div className="reading-loading-wrap">
      <div className="reading-loading-glyph"><UiIcon name="sparkle" size={48} /></div>
      <div className="reading-loading-msg">
        {messages[msgIdx]}{'·'.repeat(dot + 1)}
      </div>
      <div className="reading-loading-bar">
        <div className="reading-loading-bar-inner" />
      </div>
      <p className="reading-loading-note">Gemini is reading your chart — usually takes 5–15 seconds</p>
    </div>
  );
}

function ReadingDisplay({ reading, onNew }) {
  const focusMeta = FOCUS_AREAS.find((f) => f.value === reading.focus);
  const toast = useToast();

  const handleShare = () => {
    const text = `✦ Ephi Oracle Reading ✦\nFocus: ${focusMeta?.label || reading.focus}\n\n${reading.text}\n\nGenerated by Ephi: The Midnight Grimoire`;
    navigator.clipboard.writeText(text);
    toast('Reading copied to clipboard.');
  };

  return (
    <div className="reading-display-wrap">
      {/* Reading meta bar */}
      <div className="reading-meta">
        <div className="reading-meta-left">
          <span className="pill">
            {focusMeta?.label || reading.focus}
          </span>
          <span className="reading-time">{timeAgo(reading.timestamp)}</span>
          {reading.aspectCount > 0 && (
            <span className="reading-aspect-count">{reading.aspectCount} active transits</span>
          )}
        </div>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button className="btn btn-ghost" onClick={() => window.print()} style={{ padding: '0.4rem 0.8rem', fontSize: '0.75rem' }}>
            <UiIcon name="pin" size={12} style={{ marginRight: 6 }} />
            Print to Grimoire
          </button>
          <button className="btn btn-ghost" onClick={handleShare} style={{ padding: '0.4rem 0.8rem', fontSize: '0.75rem' }}>
            <UiIcon name="sparkle" size={12} style={{ marginRight: 6 }} />
            Share
          </button>
          <button className="btn btn-ghost" onClick={onNew} style={{ padding: '0.4rem 0.8rem', fontSize: '0.75rem' }}>
            New reading
          </button>
        </div>
      </div>

      {/* Reading body */}
      <div className="reading-body card">
        <EphiMarkdown text={reading.text} />
        
        <div style={{ 
          marginTop: '2rem', 
          paddingTop: '1rem', 
          borderTop: '1px dashed var(--border)',
          textAlign: 'center'
        }}>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
            Found this reading helpful?
          </p>
          <Link 
            to="/support" 
            style={{ 
              color: 'var(--accent)', 
              fontSize: '0.75rem', 
              fontWeight: '700', 
              textDecoration: 'none',
              textTransform: 'uppercase',
              letterSpacing: '0.1em'
            }}
          >
            ✦ Support the Oracle
          </Link>
        </div>
      </div>

      {/* Footer */}
      <div className="reading-footer">
        <span>Generated by Gemini Flash · </span>
        <Link to="/dashboard" className="reading-back-link">← Back to live transits</Link>
      </div>
    </div>
  );
}

function PastReadings({ readings, onSelect }) {
  if (!readings.length) return null;
  return (
    <div className="reading-past-wrap">
      <div className="reading-past-label">Past readings</div>
      {readings.map((r, i) => {
        const focusMeta = FOCUS_AREAS.find((f) => f.value === r.focus);
        return (
          <button key={i} className="reading-past-item" onClick={() => onSelect(r)}>
            <span className="reading-past-emoji">{focusMeta?.emoji || '✦'}</span>
            <span className="reading-past-focus">{focusMeta?.label || r.focus}</span>
            <span className="reading-past-time">{timeAgo(r.timestamp)}</span>
            <span className="reading-past-chevron">›</span>
          </button>
        );
      })}
    </div>
  );
}

function NoKeyBanner() {
  return (
    <div className="reading-banner-wrap">
      <div className="reading-banner-icon"><UiIcon name="gear" size={48} color="var(--accent)" /></div>
      <div className="reading-banner-title">Gemini API key not configured</div>
      <p className="reading-banner-text">
        To enable AI readings, add your free Gemini API key to a <code>.env</code> file
        in your project root:
      </p>
      <div className="reading-code-block">
        VITE_GEMINI_API_KEY=your_key_here
      </div>
      <p className="reading-banner-text">
        Get a free key at{' '}
        <a href="https://aistudio.google.com" target="_blank" rel="noreferrer" className="reading-link">
          aistudio.google.com
        </a>
        {' '}— no credit card required.
      </p>
      <Link to="/dashboard" className="btn btn-primary" style={{ marginTop: '2rem' }}>← Back to transit dashboard</Link>
    </div>
  );
}

function NoNatalBanner() {
  return (
    <div className="reading-banner-wrap">
      <div className="reading-banner-icon"><PlanetIcon name="moon" size={48} color="var(--accent)" /></div>
      <div className="reading-banner-title">No natal chart found</div>
      <p className="reading-banner-text">
        You need to enter your birth details first so the AI can personalise your reading.
      </p>
      <Link to="/dashboard" className="btn btn-primary" style={{ marginTop: '2rem' }}>← Set up your natal chart</Link>
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function ReadingPage() {
  const navigate = useNavigate();

  const [natal,       setNatal]       = useState(null);
  const [aspects,     setAspects]     = useState([]);
  const [focus,       setFocus]       = useState('general');
  const [mode,        setMode]        = useState('transit');
  const [status,      setStatus]      = useState('idle'); // idle | loading | done | error
  const [reading,     setReading]     = useState(null);
  const [errorMsg,    setErrorMsg]    = useState('');
  const [configured,  setConfigured]  = useState(true);
  const [pastReadings,setPastReadings]= useState([]);
  const [deepDive,    setDeepDive]    = useState(null); // { planet, text, loading }
  const [puristMode,  setPuristMode]  = useState(false);
  const [userQuery,   setUserQuery]   = useState('');
  const [confirmModal,setConfirmModal]= useState(null);
  const abortRef = useRef(false);

  // Load data on mount
  useEffect(() => {
    const settings = store.getJSON('ephi_settings') || {};
    setPuristMode(settings.puristMode || false);

    setConfigured(isGeminiConfigured());
    const natalData = getNatalFromStorage();
    setNatal(natalData);

    const aspectData = getAspectsFromStorage();
    if (aspectData?.aspects) {
      setAspects(aspectData.aspects);
    }

    const loadPast = async () => {
      const past = await getRecentReadings();
      setPastReadings(past);
    };
    loadPast();
  }, []);

  // Fetch fresh aspects if not cached
  useEffect(() => {
    if (!natal || aspects.length > 0) return;

    function calcAspects() {
      try {
        const now = new Date();
        const transitPositions = getPlanetPositions(now);
        const natalPositions = natal.positions;
        
        const tn = getActiveAspects(transitPositions, natalPositions);
        setAspects(tn || []);
        
        // Cache for this session
        store.setJSON('astro_aspects', { aspects: tn, timestamp: now.toISOString() });
      } catch (err) {
        console.error('Failed to calculate aspects locally:', err);
      }
    }

    calcAspects();
  }, [natal]);

  async function handleGenerate() {
    if (!natal) return;

    const existingFresh = await getLatestReading(focus);
    if (existingFresh) {
      const focusLabel = FOCUS_AREAS.find(f => f.value === focus)?.label || focus;
      setConfirmModal({
        focusLabel,
        timeAgoStr: timeAgo(existingFresh.timestamp),
        existingFresh
      });
      return;
    }

    executeGeneration();
  }

  async function executeGeneration() {
    abortRef.current = false;
    setStatus('loading');
    setErrorMsg('');
    setReading(null);

    try {
      const result = await generateReading({ 
        natal, 
        aspects, 
        focus, 
        userQuery: focus === 'custom' ? userQuery : '',
        mode
      });
      if (abortRef.current) return;

      const saved = await saveReading({
        focus,
        text: result.text,
        aspects,
        aspectCount: aspects.length,
      });

      const past = await getRecentReadings();
      setPastReadings(past);
      setReading(saved);
      setStatus('done');
    } catch (err) {
      if (abortRef.current) return;
      setErrorMsg(err.message || 'Failed to generate reading.');
      setStatus('error');
    }
  }

  function handleNewReading() {
    setReading(null);
    setStatus('idle');
    setErrorMsg('');
  }

  function handleSelectPast(r) {
    setReading(r);
    setStatus('done');
  }

  async function handlePlanetClick(planet, set) {
    setDeepDive({ planet, loading: true, text: '' });
    try {
      const res = await generateAspectReading({
        transitPlanet: planet,
        natalPlanet: planet, // Simple self-reflection for hotspots
        aspectName: 'conjunction',
        natal
      });
      setDeepDive({ planet, loading: false, text: res.text });
    } catch (err) {
      setDeepDive({ planet, loading: false, text: 'The Oracle is silent on this planet today.' });
    }
  }

  async function handleAspectClick(asp) {
    const transitP = asp.transitPlanet || asp.planet1;
    const natalP = asp.natalPlanet || asp.planet2;
    setDeepDive({ planet: `${transitP} ${asp.aspectName} ${natalP}`, loading: true, text: '' });
    try {
      const res = await generateAspectReading({
        transitPlanet: transitP,
        natalPlanet: natalP,
        aspectName: asp.aspectName,
        natal
      });
      setDeepDive({ planet: `${transitP} ${asp.aspectName} ${natalP}`, loading: false, text: res.text });
    } catch (err) {
      setDeepDive({ planet: 'Aspect Deep-Dive', loading: false, text: 'The Oracle is silent on this connection.' });
    }
  }

  // ── Render guards ──────────────────────────────────────────────────────────
  if (!configured) return <NoKeyBanner />;
  if (natal === null && status === 'idle') return (
    <div className="page-wrap">
      <div className="reading-loading-wrap">
        <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Loading…</div>
      </div>
    </div>
  );
  if (!natal) return <NoNatalBanner />;

  // ── Done — show reading ────────────────────────────────────────────────────
  if (status === 'done' && reading) {
    return (
      <div className="page-wrap">
        <ReadingDisplay reading={reading} onNew={handleNewReading} />
        <PastReadings readings={pastReadings.slice(1)} onSelect={handleSelectPast} />
      </div>
    );
  }

  // ── Loading ────────────────────────────────────────────────────────────────
  if (status === 'loading') {
    return (
      <div className="page-wrap">
        <LoadingState focus={focus} />
      </div>
    );
  }

  // ── Idle / error — main UI ─────────────────────────────────────────────────
  return (
    <div className="page-wrap">
      {/* Page header */}
      <div className="page-header">
        <span className="page-label">The Oracle</span>
        <h1 className="page-title">
          <UiIcon name="sparkle" size={28} color="var(--accent)" style={{ marginRight: '12px' }} />
          AI Reading
        </h1>
        <p className="page-subtitle">
          Gemini synthesizes your natal chart with today's live transits into a personalised reading.
        </p>
      </div>

      <AdSlot type="banner" slotId="reading-top" />

      {/* Interactive Chart Wheel */}
      <div className="chart-container" style={{ marginBottom: '3rem' }}>
        <ChartWheel 
          planets={natal?.positions || {}} 
          ascendant={natal?.asc || 0}
          size={Math.min(window.innerWidth - 40, 500)}
          bgColor="var(--bg-card)"
          strokeColor="var(--border)"
          onPlanetClick={handlePlanetClick}
          onAspectClick={handleAspectClick}
        />
        <p style={{ textAlign: 'center', fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '1rem' }}>
          ✦ Click any planet for a specialized deep-dive reading.
        </p>
      </div>

      {/* Natal summary */}
      <div className="reading-natal-summary card" style={{ textAlign: 'center' }}>
        <div className="reading-natal-label">Reading for</div>
        <div className="reading-natal-value">
          {natal.meta?.birthDate || 'your natal chart'}
          {natal.meta?.birthCity ? ` · ${natal.meta.birthCity}` : ''}
        </div>
      </div>

      {/* Active aspects count */}
      {aspects.length > 0 && (
        <div className="reading-aspects-summary">
          <span className="reading-aspects-dot" />
          <span className="reading-aspects-text">
            {aspects.filter(a => ['exact','strong'].includes(a.strength)).length} significant transits active now
          </span>
        </div>
      )}

      {/* Reading Type selector */}
      <div className="reading-section">
        <div className="reading-section-title">Reading Type</div>
        <div style={{ display: 'flex', gap: '0.5rem', background: 'var(--bg-card)', padding: '4px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
          <button 
            className={`btn ${mode === 'transit' ? 'btn-primary' : 'btn-ghost'}`}
            style={{ flex: 1, padding: '0.75rem', borderRadius: '4px', fontSize: '0.9rem' }}
            onClick={() => setMode('transit')}
            disabled={status === 'loading'}
          >
            Transit Forecast
          </button>
          <button 
            className={`btn ${mode === 'natal' ? 'btn-primary' : 'btn-ghost'}`}
            style={{ flex: 1, padding: '0.75rem', borderRadius: '4px', fontSize: '0.9rem' }}
            onClick={() => setMode('natal')}
            disabled={status === 'loading'}
          >
            Natal Blueprint
          </button>
        </div>
        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.75rem', textAlign: 'center' }}>
          {mode === 'transit' ? "Analyzes how today's active transits are triggering your chart." : 'A timeless deep dive into your fundamental soul architecture.'}
        </p>
      </div>

      {/* Focus selector */}
      <div className="reading-section">
        <div className="reading-section-title">Choose your focus</div>
        <FocusSelector
          selected={focus}
          onChange={setFocus}
          disabled={status === 'loading'}
        />
      </div>

      {/* Custom Inquiry Box */}
      {focus === 'custom' && (
        <div className="reading-section">
          <div className="reading-section-title">Your Question</div>
          <textarea
            className="reading-inquiry-box"
            placeholder="e.g. 'What does my chart say about my hidden talents?' or 'Will I move abroad this year?'"
            value={userQuery}
            onChange={(e) => setUserQuery(e.target.value)}
            disabled={status === 'loading'}
          />
          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.5rem' }}>
            Be specific! Mention the life area or transition you're curious about.
          </p>
        </div>
      )}

      {/* Error */}
      {status === 'error' && (
        <div className="reading-error-box">
          <UiIcon name="warning" size={16} />
          <span>{errorMsg}</span>
        </div>
      )}

      {/* Generate button */}
      <div className="reading-generate-wrap">
        <button className="btn btn-primary" onClick={handleGenerate} style={{ width: '100%', padding: '1rem' }}>
          <UiIcon name="sparkle" size={18} />
          Generate {FOCUS_AREAS.find(f => f.value === focus)?.label} Reading
        </button>
        <p className="reading-generate-note">
          Uses ~1 of your 15 free Gemini requests per minute
        </p>
      </div>

      {/* Past readings */}
      <PastReadings readings={pastReadings} onSelect={handleSelectPast} />

      {/* Confirm Modal */}
      {confirmModal && (
        <div className="reading-modal-overlay">
          <div className="reading-modal-content card">
            <div className="reading-modal-icon"><UiIcon name="sparkle" size={32} /></div>
            <h3 className="card-title">Existing Reading Found</h3>
            <p className="reading-modal-text">
              You already have a <strong>{confirmModal.focusLabel}</strong> reading generated {confirmModal.timeAgoStr}. Would you like to generate a new one or view the existing one?
            </p>
            <div className="reading-modal-actions">
              <button
                className="btn btn-ghost"
                onClick={() => {
                  setReading(confirmModal.existingFresh);
                  setStatus('done');
                  setConfirmModal(null);
                }}
              >
                View Existing
              </button>
              <button
                className="btn btn-primary"
                onClick={() => {
                  setConfirmModal(null);
                  executeGeneration();
                }}
              >
                Generate New
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Deep Dive Modal */}
      {deepDive && (
        <div className="reading-modal-overlay" onClick={() => setDeepDive(null)}>
          <div className="reading-modal-content card" style={{ maxWidth: '600px', maxHeight: '80vh', overflowY: 'auto' }} onClick={e => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <div style={{ padding: '10px', background: 'var(--bg-deep)', borderRadius: '10px', border: '1px solid var(--border)' }}>
                  <UiIcon name="sparkle" size={20} color="var(--accent)" />
                </div>
                <h3 style={{ margin: 0, fontSize: '1.2rem', textTransform: 'capitalize' }}>{deepDive.planet} Deep-Dive</h3>
              </div>
              <button onClick={() => setDeepDive(null)} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: '1.5rem' }}>×</button>
            </div>

            {deepDive.loading ? (
              <div style={{ padding: '3rem', textAlign: 'center' }}>
                <div className="spinner" style={{ margin: '0 auto 1rem' }} />
                <p>Consulting the archives...</p>
              </div>
            ) : (
              <div className="reading-body" style={{ padding: 0 }}>
                <EphiMarkdown text={deepDive.text} />
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
